apiVersion: v1 
kind: Secret
metadata:
  name: rabbitmq
  labels:
    purpose: rabbitmq
    project: roboshop
    app: database
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: "Ucm9ib3Nob3A="
  RABBITMQ_DEFAULT_PASS: "m9ib3Nob3AxMjM="
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    purpose: rabbitmq
    project: roboshop
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      purpose: rabbitmq
      project: roboshop
      app: database
  template:
    metadata:
      labels:
        purpose: rabbitmq
        project: roboshop
        app: database
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        envFrom:
        - SecretRef:
            name: rabbitmq

---
apiVersion: v1 
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    purpose: rabbitmq
    project: roboshop
    app: database
spec:
  selector:
    purpose: rabbitmq
    project: roboshop
    app: database
  ports:
  - Protocol: TCP
    port: 5672
    targetPort: 5672

