apiVersion: v1 
kind: Secret
metadata:
  name: mysql
  labels:
    purpose: mysql
    project: roboshop
    app: database
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "Um9ib1Nob3BAMQ=="


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels:
    purpose: mysql
    project: roboshop
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      purpose: mysql
      project: roboshop
      app: database
  template:
    metadata:
      labels:
        purpose: mysql
        project: roboshop
        app: database
    spec:
      containers:
      - name: mysql
        image: syam/mysql:v1
        envFrom:
        - SecretRef:
            name: mysql

---
apiVersion: v1 
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    purpose: mysql
    project: roboshop
    app: database
spec:
  selector:
    purpose: mysql
    project: roboshop
    app: database
  ports:
  - Protocol: TCP
    port: 3306 #service port 
    targetPort: 3306 #container port

