apiVersion: v1 
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
  labels:
    purpose: user
    project: roboshop
    tier: app
data:
  MONGO: true
  REDIS_URL: "redis://redis:6379"
  MONGO_URL: "mongodb://mongodb:27017/users"
---

apiVersion: tiers/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels:
    purpose: user
    project: roboshop
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      purpose: user
      project: roboshop
      tier: app
  template:
    metadata:
      labels:
        purpose: user
        project: roboshop
        tier: app
    spec:
      containers:
      - name: user
        image: syam/user:v1
        envFrom:
        - ConfigMapRef:
            name: user

---
apiVersion: v1 
kind: Service
metadata:
  name: user
  namespace: roboshop
  labels:
    purpose: user
    project: roboshop
    tier: app
spec:
  selector:
    purpose: user
    project: roboshop
    tier: app
  ports:
  - Protocol: TCP
    port: 8080
    targetPort: 8080
